config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :contacts
  resources :abouts
  resources :tutorials
  resources :homes

root 'homes#index'
end

app/models/about.rb
class About < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :message, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
  validates :demo_link, presence: true
  validates :download_link, presence: true

  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
  validates :tutorial_link, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  def index
    @pagy, @abouts = pagy(About.all.order('created_at asc'), items: 1)
  end

  def show
    @about = About.find(params[:id])
    @abouts = About.order('created_at asc').limit(4).offset(1)
  end

  private
    def set_about
      @about = About.find(params[:id])
    end

    def about_params
      params.require(:about).permit(:title, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
    @contacts = Contact.order('created_at desc').limit(4).offset(1)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html do
          flash[:success] = 'Message Sent!'
          redirect_to contacts_url
        end
      else
        format.html { flash[:failure!] = 'Message Not Sent! Verify Details & Send Again!' }
        format.html { render :new }
      end
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:email, :message)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  def index
    @pagy, @homes = pagy(Home.all.order('created_at DESC'), items: 8)
  end

  def show
    @home = Home.find(params[:id])
    @homes = Home.order('created_at desc').limit(4).offset(1)
  end

  private
  def set_home
    @home = Home.find(params[:id])
  end

  def home_params
    params.require(:home).permit(:title, :body, :demo_link, :download_link)
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]

  def index
    @tutorials = Tutorial.all
    @pagy, @tutorials = pagy(Tutorial.all.order('created_at DESC'), items: 4)
  end

  def show
    @tutorial = Tutorial.find(params[:id])
    @tutorials = Tutorial.order('created_at desc').limit(4).offset(1)
  end

  private
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end

    def tutorial_params
      params.require(:tutorial).permit(:title, :body, :tutorial_link)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
  include Pagy::Frontend
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  include Pagy::Frontend
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
  include Pagy::Frontend
end

app/views/abouts/_form.html.erb
<%= form_with(model: about, local: true) do |form| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<!-- Header -->
<header class="w3-display-container w3-content w3-center" id="home" style="max-width:1500px">
  <div class="bgimg-2 w3-display-container w3-opacity-min">
    <div class="w3-display-middle w3-padding-large w3-border w3-wide w3-text-light-grey w3-center">
      <h2 class="w3-hide-medium w3-hide-small"><b>ABOUT</b></h2>
      <h3 class="w3-hide-large"><b>ABOUT</b></h3>
    </div>
  </div>
</header>

<!-- Page content -->
<div class="w3-container w3-padding-large w3-light-grey">
  <!-- Back -->
  <a href="homes" class="w3-bar-item w3-button w3-padding-large w3-hover-grey" title="back"><i class="fa fa-arrow-left w3-hover-opacity"></i></i></a>

<!-- About Section -->
  <div class="w3-container w3-content w3-center w3-padding-64 w3-light-grey" style="max-width:800px">
    <h2 class="w3-wide">Key features</h2>
    <div class="w3-row-padding w3-center" style="margin-top:64px">
      <div class="w3-quarter">
        <i class="fa fa-desktop w3-margin-bottom w3-jumbo w3-center"></i>
      </div>
      <div class="w3-quarter">
        <i class="fa fa-heart w3-margin-bottom w3-jumbo"></i>
      </div>
      <div class="w3-quarter">
        <i class="fa fa-diamond w3-margin-bottom w3-jumbo"></i>
      </div>
      <div class="w3-quarter">
        <i class="fa fa-cog w3-margin-bottom w3-jumbo"></i>
      </div>
    </div>

    <% @abouts.each do |about| %>
      <p class="w3-opacity"><i><%= about.title %></i></p>
      <p class="w3-justify"><%= about.body %></p>
    <% end %>

  </div>

  <div class="w3-bar w3-center w3-padding-large">
    <b><i><%== pagy_nav(@pagy) %></i></b>
  </div> 
    
  <div class="w3-row w3-padding-32">
    <div class="w3-center">
      <img src="assets/about_image.jpg" class="w3-circle w3-margin-bottom" alt="Elly Ambet" style="width:10%">
      <p class="w3-opacity"><i><b>Elly Ambet</b></i></p>
      <b><i>Software Developer.</i></b>
    </div>
  </div>

<!-- End page content -->
</div>  

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @about.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @about.body %>
</p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<!-- Header -->
<header class="w3-display-container w3-content w3-center" id="home" style="max-width:1500px">
  <div class="bgimg-3 w3-display-container w3-opacity-min">
    <div class="w3-display-middle w3-padding-large w3-border w3-wide w3-text-light-grey w3-center">
      <h2 class="w3-hide-medium w3-hide-small"><b>CONTACTS</b></h2>
      <h3 class="w3-hide-large"><b>CONTACTS</b></h3>
    </div>
  </div>
</header>

<!-- Page content -->
<div class="w3-container w3-padding-large w3-white">

  <!-- Back -->
  <a href="homes" class="w3-bar-item w3-button w3-padding-large w3-hover-grey" title="back"><i class="fa fa-arrow-left w3-hover-opacity"></i></i></a>

  <!-- Container (Contact Section) -->
  <div class="w3-padding-64 w3-light-grey">
    <div class="w3-row w3-padding-32 w3-section">
      <div class="w3-col m4 w3-container">
        <div class="w3-large w3-margin-bottom">
          <i class="fa fa-map-marker fa-fw w3-hover-text-black w3-xlarge w3-margin-right"></i> Nairobi, Kenya<br>
          <i class="fa fa-phone fa-fw w3-hover-text-black w3-xlarge w3-margin-right"></i> Phone: +254 703103579<br>
          <i class="fa fa-envelope fa-fw w3-hover-text-black w3-xlarge w3-margin-right"></i> Email: e37@elitesketch.com<br>
        </div>
      </div>
      <div class="w3-col m8 w3-panel">
        <%= form_for Contact.new, url: {action: "create"}, html: {class: "single-form quate-form"} do |f| %>
          <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
            <div class="w3-half">
              <%= f.text_field :email, placeholder: 'Email', class: 'w3-input w3-border form-control' %>
            </div>
            <div class="w3-half">
              <%= f.text_area :message, placeholder: 'Message', class: 'w3-input w3-border form-control' %>
            </div>
          </div>
          <button class="w3-button w3-black w3-right w3-section" type="submit">
            <i class="fa fa-paper-plane" id="form-submit"></i> SEND MESSAGE
          </button>
        <% end %>

        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
      </div>
    </div>
  </div>

<!-- End page content -->
</div> 

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :demo_link %>
    <%= form.text_field :demo_link %>
  </div>

  <div class="field">
    <%= form.label :download_link %>
    <%= form.text_field :download_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<!-- Header -->
<header class="w3-display-container w3-content w3-center" id="home" style="max-width:1500px">
  <!-- Hide small -->
  <div class="header-wrapper">
    <img class="w3-image" style="background-color:rgb(2, 20, 2);" src="assets/banner.jpg" alt="banner" width="1500" height="300">
    <div class="w3-display-middle w3-padding-large w3-border w3-wide w3-text-light-grey w3-center">
      <img class="w3-image" src="assets/logo.jpg" alt="logo" width="200" height="100">
      <h3 class="w3-hide-medium w3-hide-small">ES TEMPLATES</h3>
    </div>
  </div>

  <!-- Navbar (placed at the bottom of the header image) -->
  <div class="w3-bar w3-light-grey w3-round w3-display-bottommiddle w3-hide-small" style="bottom:-16px">
    <a href="tutorials" class="w3-bar-item w3-button">Tutorials</a>
    <a href="abouts" class="w3-bar-item w3-button">About</a>
    <a href="contacts" class="w3-bar-item w3-button">Contact</a>
  </div>
</header>

<!-- Navbar on small screens -->
<div class="w3-center w3-blue-gray w3-padding-16 w3-hide-large w3-hide-medium">
<div class="w3-bar w3-light-grey">
  <a href="tutorials" class="w3-bar-item w3-button">Tutorials</a>
  <a href="abouts" class="w3-bar-item w3-button">About</a>
  <a href="contacts" class="w3-bar-item w3-button">Contact</a>
</div>
</div>

<!-- Page content -->
<div class="w3-container w3-padding-large w3-light-grey">

  <!-- Template Section -->
  <div class="w3-content w3-padding-64 w3-light-grey">
      <% @homes.each do |home| %>
        <%= image_tag home.image.url, class: "w3-image" %>
        <h1 class="w3-xlarge w3-text-dark-grey"><b><%= home.title %></b></h1>
        <p class="w3-text-dark-grey"><b><i><%= home.body %></i></b></p>

        <div class="w3-panel w3-bottombar w3-border-blue-grey">
          <button class="w3-button w3-light-grey w3-padding-large w3-section">
            <i class="fa fa-check"></i> Demo
          </button>
          <button class="w3-button w3-light-grey w3-padding-large w3-section" onclick="document.getElementById('download').style.display='block'">
            <i class="fa fa-download"></i> Download
          </button>
        </div>
      <% end %>
  </div>

  <div class="w3-bar w3-center w3-padding-large">
    <b><i><%== pagy_nav(@pagy) %></i></b>
  </div> 

  <!-- Modal -->
  <div id="download" class="w3-modal w3-animate-opacity">
    <div class="w3-modal-content" style="padding:32px">
      <div class="w3-container w3-white">
        <i onclick="document.getElementById('download').style.display='none'" class="fa fa-remove w3-xlarge w3-button w3-transparent w3-right w3-xlarge"></i>
        <h4>DOWNLOAD</h4>
        <p>Download the template!</p>
        <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
        <button type="button" class="w3-button w3-block w3-padding-large w3-blue-gray w3-hover-gray w3-margin-bottom" onclick="document.getElementById('download').style.display='none'">Download</button>
      </div>
    </div>
  </div>

<!-- End page content -->
</div> 

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @home.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @home.body %>
</p>

<p>
  <strong>Demo link:</strong>
  <%= @home.demo_link %>
</p>

<p>
  <strong>Download link:</strong>
  <%= @home.download_link %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>EliteSketch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="icon" type="image/ico" href="assets/favicon.png">

    <link rel="stylesheet" href="assets/stylesheets/w3css/style.css">
  </head>

  <body class="w3-light-grey">
    <%= render 'shared/header' %>
    <%= render 'shared/alerts' %>
      <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<!--
|========================
|      Script
|========================
-->
<script src="assets/javascripts/script/main.js"></script>

<!-- Footer -->
<div class="w3-padding-large w3-blue-gray">
  <footer class="w3-center">
    <p>
      <i class="fa fa-envelope"> P.O.Box 1231-00232</i><br>
      <i>Copyright &copy; 2019 EliteSketch.</i>
    </p>
  </footer>
</div>

app/views/shared/_header.html.erb
<!-- Navigation bar -->
<div class="w3-top w3-light-grey">
  <div class="w3-bar" id="myNavbar">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right w3-hover-blue-gray" href="javascript:void(0)" onclick="toggleFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="homes" class="w3-bar-item w3-button w3-padding-large w3-hover-blue-grey" title="Home"><i class="fa fa-home w3-hover-opacity"></i></a>
    <a href="https://github.com/elibiz443" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hover-blue-gray" title="github"><i class="fa fa-github w3-hover-opacity"></i></i></i></a>
    <a href="https://twitter.com/OAmbet" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hover-blue-gray" title="twitter"><i class="fa fa-twitter w3-hover-opacity"></i></i></i></a>
    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-large w3-right w3-hover-blue-gray w3-hide-small w3-right" title="Search"><i class="fa fa-search w3-hover-opacity"></i></a>
  </div>
</div>

<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->
<div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">
  <a href="https://github.com/elibiz443" class="w3-bar-item w3-button w3-padding-large" title="Github" onclick="toggleFunction()"><i class="fa fa-github"></i></a>
  <a href="https://twitter.com/OAmbet" class="w3-bar-item w3-button w3-padding-large" title="Twitter" onclick="toggleFunction()"><i class="fa fa-twitter"></i></a>
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-large" title="Search" onclick="toggleFunction()"><i class="fa fa-search"></i></a>
</div>

app/views/tutorials/_form.html.erb
<%= form_with(model: tutorial, local: true) do |form| %>
  <% if tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% tutorial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :tutorial_link %>
    <%= form.text_field :tutorial_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tutorials/edit.html.erb
<h1>Editing Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<!-- Header -->
<header class="w3-display-container w3-content w3-center" id="home" style="max-width:1500px">
  <div class="bgimg-1 w3-display-container w3-opacity-min">
    <div class="w3-display-middle w3-padding-large w3-border w3-wide w3-text-light-grey w3-center">
      <h2 class="w3-hide-medium w3-hide-small"><b>TUTORIALS</b></h2>
      <h3 class="w3-hide-large"><b>TUTORIALS</b></h3>
    </div>
  </div>
</header>

<!-- Page content -->
<div class="w3-container w3-padding-large w3-white">

  <!-- Back -->
  <a href="homes" class="w3-bar-item w3-button w3-padding-large w3-hover-grey" title="back"><i class="fa fa-arrow-left w3-hover-opacity"></i></i></a>

  <h2 class="w3-wide">Featured Tutorials.</h2>
  <div class="w3-row-padding w3-center" style="margin-top:64px">
    <div class="w3-quarter">
      <i class="fa fa-laptop w3-margin-bottom w3-jumbo w3-center"></i>
      <h4><i>Dynamic Sites.</i></h4>
    </div>
    <div class="w3-quarter">
      <i class="fa fa-tablet w3-margin-bottom w3-jumbo"></i>
      <h4><i>Static Sites.</i></h4>
    </div>
    <div class="w3-quarter">
      <i class="fa fa-database w3-margin-bottom w3-jumbo"></i>
      <h4><i>Databases.</i></h4>
    </div>
    <div class="w3-quarter">
      <i class="fa fa-arrow-right w3-margin-bottom w3-jumbo"></i>
      <h4><i>Deploying Apps.</i></h4>
    </div>
  </div>

  <!-- Tutorial Section -->
  <% @tutorials.each do |tutorial| %>
    <div class="w3-padding-64 w3-light-grey">
      <div class="w3-row-padding">
        <div class="w3-col w3-light-grey l8 m6 w3-hide-small" style="width:100%">
          <h1 class="w3-xlarge w3-text-dark-grey"><b><%= tutorial.title %></b></h1>
          <iframe class="w3-container w3-light-grey" style="width:50%" src="https://www.youtube.com/embed/tgbNymZ7vqY"></iframe>
          <div class="w3-right" style="width:45%">
            <ul class="w3-ul w3-border">
             <li><%= tutorial.body %></li>
            </ul>
          </div>
        </div>
        <!--Tutorial Section On small devices -->
        <div class="w3-col w3-light-grey l4 m6 w3-hide-large w3-hide-medium" style="width:100%">
          <h3 class="w3-large w3-text-dark-grey"><b><%= tutorial.title %></b></h3>
          <iframe class="w3-container w3-light-grey" style="width:95%" src="<%= tutorial.tutorial_link %>"></iframe>
          <div style="width:95%">
            <p><%= tutorial.body %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="w3-bar w3-center w3-padding-large">
    <b><i><%== pagy_nav(@pagy) %></i></b>
  </div> 

<!-- End page content -->
</div>  

app/views/tutorials/new.html.erb
<h1>New Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tutorial.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @tutorial.body %>
</p>

<p>
  <strong>Tutorial link:</strong>
  <%= @tutorial.tutorial_link %>
</p>

<%= link_to 'Edit', edit_tutorial_path(@tutorial) %> |
<%= link_to 'Back', tutorials_path %>